apiVersion: apps/v1
kind: Deployment
metadata:
  name: webinar-test-alpine
  namespace: webinar-test
spec:
  replicas: 3
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
      - name: alpine
        image: alpine:latest
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"